### PR TITLE
Update models.py

### PR DESCRIPTION
**Pull request by rakekniven**
Wording changes due to discussions at Transifex.
https://www.transifex.com/nextcloud/nextcloud/translate/#de_DE/appstore/98030072

### CODE REVIEW

**Comment by BernhardPosselt** [comment]
Hm, doesn't really fit that well. This stuff is about keeping track of deleted app releases so we can update the http etag properly

**Comment by rakekniven** [comment]
To be honest we do not fully understand the meaning of the original strings.

**Comment by BernhardPosselt** [comment]
Do you think you can figure out the meaning with my description?

**Comment by comradekingu** [comment]
@BernhardPosselt So, deleted nextcloud apps?

**Comment by BernhardPosselt** [comment]
Deleted nextcloud app releases

**Pull request closed without merging**
