### PR TITLE
Allow arbitrary order of elements in info.xml

### PR DESCRIPTION
**Pull request by ChristophWurst**
@rullzer as discussed

### CODE REVIEW

**Comment by juliushaertl** [comment]
That won't work as xs:all does only allow elements with maxOccurs of 0 or 1.

**Comment by ChristophWurst** [comment]
Do you have any references for that?

https://stackoverflow.com/questions/16101488/difference-between-xsdall-and-xsdsequence-in-schema-definition#comment23005142_16101544

**Comment by juliushaertl** [comment]
Ah I wasn't aware that it is supported in XSD 1.1, anyway seems the library lxml used by the appstore doesn't support that properly, see the failing tests.

**Comment by BernhardPosselt** [comment]
Needs xsd 1.1 unfortunately which is only supported on Java and C# platforms as far as I know.

**Comment by ChristophWurst** [comment]
Dang it.

**Comment by BernhardPosselt** [comment]
Saxon C supports it http://www.saxonica.com/saxon-c/release-notes.xml

but I don't think it's integrated widely yet or available as packages on major distros.

**Pull request closed without merging**
