### PR TITLE
l10n: Add a hyphen

### PR DESCRIPTION
**Pull request by Valdnet**

### CODE REVIEW

**Review by blizzz — APPROVED** [review]

**Review by rakekniven — APPROVED** [review]

**Comment by blizzz** [comment]
the tests started to fail in master without changes. needs investigating.

**Comment by Valdnet** [comment]
@blizzz Do you know how to fix it?

**Comment by blizzz** [comment]
> @blizzz Do you know how to fix it?

no, I did not have time to look into it yet

**Comment by Valdnet** [comment]
ping @blizzz.

**Pull request merged**
