### PR TITLE
last_modified header support + optimisation

### PR DESCRIPTION
**Pull request by bigcat88**
This is a dev PR, after testing it will be adjusted if everything is ok.

The reason for this PR:
Most requests to the AppStore do not send ETag and this leads to a very high load.

~~This should help with this: the binary result of the request `/api/v1/apps.json` will be stored in Redis, and the next time if the request does not have an ETag in the header, but the response for this Etag is already in Redis, the result will be directly returned from Redis.~~

Changes in PR:

1. Added `Last Modified` header in addition to ETag, feel free to use any of this headers you like.
2. We GZip content of api/v1/apps.json and return it to Nginx, so Nginx will not gzip it on his own for every request and will just return it from cache.

_By what percentage this will reduce the load it will soon become clear; the PR will be edited with these data._

Local benchmarks(`apps.nextcloud.com` is local url in this case):

```python3

    start = perf_counter()
    for i in range(100):
        a = requests.get("https://apps.nextcloud.com/api/v1/apps.json")
    print(perf_counter() - start)
    exit()
```    

Original code:
Cold/Hot run: **27.58** / **24.42**

With this PR:
Cold/Hot run: **12.56** / **8.82**

**Expected load reduction in a production environment on the server: 2 to 4 times.**

_Still will be very high load during app release deletion or uploading, but it is another complex topic._

### CODE REVIEW

**Review by andrey18106 — APPROVED** [review]

**Comment by officialdanielamani** [comment]
I come from [https://github.com/nextcloud/appstore/issues/761](https://github.com/nextcloud/appstore/issues/761) about Appstore not show in the Nextcloud (just first time install using Docker)

image

On my Nextcloud log there are many cURL error 28  for `https://apps.nextcloud.com/api/v1/apps.json`

`{"reqId":"IzICrWBKJiXVWLTDkP9z","level":2,"time":"2023-09-26T12:50:51+00:00","remoteAddr":"10.100.42.2","user":"XXXXX","app":"appstoreFetcher","method":"GET","url":"/settings/apps","message":"Could not connect to appstore: cURL error 28: Operation timed out after 60000 milliseconds with 688128 out of 5567101 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://apps.nextcloud.com/api/v1/apps.json","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36","version":"27.1.1.0","data":{"app":"appstoreFetcher"}}`

So I try speed test on my browser and load the JSON, it took about 7-15 minute to load the JSON file
image

My average speed is between 5-30 mbps but the JSON is painfully slow. Is this cause cURL 28 error and cause Appstore not  showing on Nextcloud panel

**Comment by bigcat88** [comment]
```
curl https://apps.nextcloud.com/api/v1/apps.json > tmp.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12.1M  100 12.1M    0     0  4216k      0  0:00:02  0:00:02 --:--:-- 4222k
```

@officialdanielamani can you retry?

**Comment by officialdanielamani** [comment]
image
I try running the command on docker container, this are the current result

**Comment by andrey18106** [comment]
> image I try running the command on docker container, this are the current result

image

Tested locally and on remote server - apps.json downloading successfully by less then 1-2sec (75-100Mbit/s), so I would say that it's a slow internet connection issue.

**Comment by andrey18106** [comment]
> If I have apps.json file, can I add to Nextcloud file so I no need to lookup every time I need load. The connection speed I cannot change because it's my internet speed plan.

There is already should be local apps.json file located in `data/appdata_instanceid/appstore` folder.

**Comment by bigcat88** [comment]
What `Update channel`(settings/admin/overview) value do you have? 
It should be **stable**

If it is **stable** NC stores app.json locally automatically

image

**Comment by officialdanielamani** [comment]
I try reinstall the Nextcloud maybe it will fixed the problem. Thank you for support and guide.

**Comment by officialdanielamani** [comment]
image
I try on my fried better internet speed still have problem.

When I reinstall, there is option skip suggestion and install suggestion, but no preview of app. I click install but it just redirect to dashboard. The Appstore still missing.

**Comment by bigcat88** [comment]
I really don't know how I can help here. :(
The load on the app store server is normal, there have been no complaints/problems so far (except for this one).
All I can do is monitor the situation, and if something else comes up, maybe it will help identify a possible cause and I try to fix it, if there is anything to fix.

**Comment by bigcat88** [comment]
> The only clue is the `apps.json` on my Nextcloud the size is only 2.37MB while downloading direct from `https://apps.nextcloud.com/api/v1/categories.json` the size is over 12.1MB. On log file there is many duplicate if from direct website (and log file grew to 45MB).

This is fine, 12.1 Mb size with all applications releases info, and NC stores only releases information for it's version.

**Pull request merged**
