### PR TITLE
App list

### LINKED ISSUE #81: App list page
Apps are rendered in a minimal list atm. 

Each app section should display the first screenshot and maybe render the description (in an ellipsis) and the featured flag.

The list should be able to be sorted ascending and descending based on: 
* last_modified date (can we also include app release modified dates?)
* featured flag
* alphabetic name
* rating (if implemented)

The list should not be paginated. ATM the old app store contains a total of 250 apps which is no performance problem. Pagintation just makes the experience worse.

### PR DESCRIPTION
**Pull request by BernhardPosselt**
Fix #81 by adding sorting in the list overview

This PR also adds an additional translated field called summary. The summary is a short description which will be displayed on the app list page. Contrary to the description it will not contain markdown. If the summary field does not exist, the description field is taken.

@adsworth @janibonnevier @LukasReschke

### CODE REVIEW

**Comment by janibonnevier** [comment]
I'm getting duplicates in the alphabetical list.

**Comment by BernhardPosselt** [comment]
Hm so order_by also requires as distinct?

**Comment by janibonnevier** [comment]
There seems to be as many duplicates as there are translations.

**Comment by BernhardPosselt** [comment]
And  what I don't get is that the search call already runs a distinct on it

**Comment by janibonnevier** [comment]
Also, non-featured apps appear in the featured list.

**Comment by janibonnevier** [comment]
Adding another `distinct()` on the `order_by()` does not get rid of the duplicates.

UI-wise, I think there should be visual hint suggesting that you can reverse the ordering by clicking "Alphabetical" again, perhaps a small arrow pointing in the current ordering direction. I just discovered it by accident.

**Comment by BernhardPosselt** [comment]
Yeah we need to think about the hint :)

As for featured: do we want sorting or filtering? Currently it's sorting, that's why all apps appear in there

**Comment by janibonnevier** [comment]
In my mind a "Featured" button is definitely a filter, because I don't expect to see non-featured things if I click on it. I do see that ordering is more consistent here considering that the other buttons do ordering, but at the very least it should say which apps are featured and which are not. However, I think a better solution would be to have checkboxes for filters, and have Featured be one of them.

**Comment by adsworth** [comment]
I agree with Jani here. Featured is a filter.

**Comment by BernhardPosselt** [comment]
Check box is a good idea, probably better to remove the sorting then

**Comment by janibonnevier** [comment]
Have not yet fixed the duplicates.

**Comment by janibonnevier** [comment]
Any opinions on arrow directions?

**Comment by adsworth** [comment]
IMHO, triangle down is descending and triangle up is ascending.

**Comment by janibonnevier** [comment]
Thunar at leat does the opposite, and I guess the idea is that the arrow points toward the ascending direction in the list.

**Comment by adsworth** [comment]
you're right, the GNOME file manager does the same.

I'm not particularly biased one way or the other. So do what you think is "right".

**Pull request merged**
