### PR TITLE
Prevent guessing users

### PR DESCRIPTION
**Pull request by mario**
It is currently possible to find valid users via the password reset form. This prevents it.

Do note that this could use more polishing on the UX side, but let's merge this as a first step.

Signed-off-by: Mario Danic <mario@lovelyhq.com>

### CODE REVIEW

**Comment by BernhardPosselt** [comment]
Doesn't the reset password form simply tell you which email addresses are registered? You need a separate user name for the login.

**Comment by mario** [comment]
@BernhardPosselt sure, but why would you want to expose that?

**Comment by BernhardPosselt** [comment]
Right, I think it's best if nothing is exposed at all but I guess trying a bunch of existing E-Mails doesn't really give you a lot to work with.

We should probably fix this upstream at django-allauth since it's a low impact thing IMHO rather than handrolling a custom implementation on our own which potentially makes it harder to upgrade.

**Comment by mario** [comment]
Generally I'm fine with that, but the question remains if they'd accept such a change or not.

**Comment by BernhardPosselt** [comment]
Sure, I'd just ask first on their tracker if they are interested.

**Comment by BernhardPosselt** [comment]
https://github.com/pennersr/django-allauth/issues/2341

**Comment by mario** [comment]
Thx.

**Comment by blizzz** [comment]
Since upstream is not really active, I guess we merge this here for so long?

**Comment by BernhardPosselt** [comment]
@blizzz yeah, maybe add some comments in the source code like "remove this class once issue #xxx is resolved django-allauth" so it won't be forgotten.

**Comment by mario** [comment]
@BernhardPosselt do it! :)

**Comment by blizzz** [comment]
Not sure it is related, but the tests are failing now. @mario can you have a look, please?

**Comment by BernhardPosselt** [comment]
@blizzz problem is https://github.com/nextcloud/appstore/issues/622

**Comment by BernhardPosselt** [comment]
someone needs to fix the translations on transifex

**Comment by blizzz** [comment]
rebased

**Comment by BernhardPosselt** [comment]
We should probably add a selenium test case to to reset passwords

**Comment by mario** [comment]
@BernhardPosselt don't have time for this :( Can you do it? I'd like to have this merged and deployed (with the rest of the fixes & improvements I did) as soon as possible.

**Comment by BernhardPosselt** [comment]
Will take a look at it next week end.

**Comment by rullzer** [comment]
Then lets merge this. And do the test in a separate PR so we can deploy this

**Pull request merged**
