### PR TITLE
Add Nextcloud theming

### PR DESCRIPTION
**Pull request by LukasReschke**
First start of adding the Nextcloud website base CSS theming.

cc @BernhardPosselt @adsworth

### CODE REVIEW

**Comment by mar1u5** [comment]
👍

**Comment by adsworth** [comment]
:+1:  Nice, I'm liking the look.

**Comment by BernhardPosselt** [comment]
:+1: awesome :)

**Comment by jancborchardt** [comment]
Cool stuff, thanks @LukasReschke VP Design ;D

**Pull request merged**
