### PR TITLE
Disable integrations temporarily

### PR DESCRIPTION
**Pull request by mario**
In the mean time there's more spam.

I basically disabled the new integration URL and show the menu entry only to admins (even if it's useless, but this is a hack anyway).

Signed-off-by: Mario Danic <mario@lovelyhq.com>

### CODE REVIEW

**Comment by blizzz** [comment]
> test_transfer (nextcloudappstore.core.tests.e2e.test_owner_transfer.AppTransferTestTest) ... Forbidden: /api/v1/apps
> 
> Internal Server Error: 

@mario do you know why?

**Comment by mario** [comment]
@blizzz no, but I don't think I touched that part?

**Comment by blizzz** [comment]
:see_no_evil: :crossed_fingers:

**Comment by blizzz** [comment]
Internal Server Error: /
Traceback (most recent call last):
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 143, in _get_response
    response = response.render()
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/template/base.py", line 163, in _render                                          [0/1906]
    return self.nodelist.render(context)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/template/loader_tags.py", line 188, in render
    return template.render(context)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/template/defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/template/defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/opt/appstore/venv/lib/python3.5/site-packages/django/urls/resolvers.py", line 673, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'integration-scaffold' not found. 'integration-scaffold' is not a valid view function or pattern nam
e.

**Comment by mario** [comment]
Argh. Yea. Let me followup.

**Comment by blizzz** [comment]
> Argh. Yea. Let me followup.

thanks

**Pull request merged**
