### PR TITLE
Improve unstable detection

### PR DESCRIPTION
**Pull request by nickvergessen**
1.25.2-1 is not an unstable version
Ref https://apps.nextcloud.com/apps/talk_matterbridge

### CODE REVIEW

**Comment by SystemKeeper** [comment]
Maybe check case insensitive ?

**Comment by nickvergessen** [comment]
> Maybe check case insensitive ?

Not needed as php version_compare does not check case insensitive either. Now the handling reflects what the server does.
https://www.php.net/manual/de/function.version-compare.php

**Review by blizzz — APPROVED** [review]

**Review by blizzz — APPROVED** [review]
:snake:

**Comment by SystemKeeper** [comment]
Okay, makes sense to align that. I have no 
experience in using the NC App Store. Is this documented somewhere that this is aligned with the php Check?

**Comment by nickvergessen** [comment]
https://nextcloudappstore.readthedocs.io/en/latest/developer.html#info-xml states semantic version

**Review by CarlSchwan — APPROVED** [review]

**Comment by nickvergessen** [comment]
Can we get this deployed?
cc @blizzz

**Pull request merged**
