### PR TITLE
Django 3 and port away from recaptcha and pyenv

### LINKED ISSUE #833: Recaptcha broken at user registration
Please provide the following details for error reports from https://apps.nextcloud.com/. Ignore in case of a feature request.

## Details

* Browser and browser version:

Vivaldi | 3.7.2218.58 (Stable channel) (x86_64)
Revision | c5602492bfee983ae50345020ace09854e38bcf5
OS | macOS Version 10.14.6 (Build 18G8012)
JavaScript | V8 8.9.255.25
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.128 Safari/537.36

## JavaScript Console Output

Refused to frame 'https://google.com/' because it violates the following Content Security Policy directive: "frame-src https://www.google.com/recaptcha/".

## Steps to reproduce

1. Open https://apps.nextcloud.com/signup/  with Vivaldi Browser

Screenshot 2021-04-22 at 21 49 26
Screenshot 2021-04-22 at 21 52 19

### PR DESCRIPTION
**Pull request by BernhardPosselt**
This PR ports Django2 to Django 3.2. This also remove the dependency on recaptcha (replaced simple django captcha) and use poetry for the dependency management instead of pip and pyenv.

Fix #833

### CODE REVIEW

**Comment by BernhardPosselt** [comment]
@nickvergessen do you know what version we are running currently? this update requires Python 3.6

**Comment by nickvergessen** [comment]
cc @blizzz

**Comment by blizzz** [comment]
It's 2.7 and 3.5 at the moment.

**Comment by BernhardPosselt** [comment]
2.2 will be supported for quite some time see: https://www.djangoproject.com/download/

Nonetheless we should have a strategy for upgrading to a newer distro? and Python version at some point.

**Comment by blizzz** [comment]
In the middle run, we ought to migrate away from the current server and do a fresh setup. There is no time line however.

**Comment by blizzz** [comment]
> 3.5 at the moment.

That was a mistake or a typo. It is 3.6 by  Ubuntu 18.04.

**Comment by blizzz** [comment]
3.0 already dead, should move to 3.2, which is LTS, too

**Review by blizzz — APPROVED** [review]
looks great as far as i can say

**Pull request merged**
