### PR TITLE
feat: app-discover API

### PR DESCRIPTION
**Pull request by susnux**
* For [42547](https://github.com/nextcloud/server/issues/42547)

This includes the data format documentation for the app-discover section. Including the schema for validation.

Screenshot 2024-02-19 at 19-42-04 Appstore discover section API — AppStore 4 3 3 documentation

### CODE REVIEW

**Comment by bigcat88** [comment]
Should AppStore perform validation on upload?
Or it will be done in "upload script" before uploading?

**Comment by susnux** [comment]
I would do it on upload, there are some good libraries:

https://json-schema.org/implementations#validators-python

**Comment by susnux** [comment]
An example that validates (I use `jschon` locally):

[example.json](https://github.com/nextcloud/appstore/files/14374451/example.json)

**Comment by bigcat88** [comment]
Can we merge this or there will be more changes?

**Comment by susnux** [comment]
Can we wait a few days so I can test this for server? Otherwise we maybe need to adjust it afterwards.

**Review by bigcat88 — APPROVED** [review]

**Pull request merged**
