### PR TITLE
Cache DB queries

### PR DESCRIPTION
**Pull request by mario**
Results in caching queries (and invalidating the cache on create/update/delete) to speed things up.

WIP.
Signed-off-by: Mario Danic <mario@lovelyhq.com>

### CODE REVIEW

**Comment by mario** [comment]
@BernhardPosselt could you test this pls?

**Comment by BernhardPosselt** [comment]
The django-cachalot is unmaintained and DB level caching is extremely dangerous since it breaks assumptions. Furthermore I'd like to avoid more Django dependencies if possible since they make upgrading hell.

I'd much rather see very direct caching (like last modified timestamps and etags) that work on HTTP level. An obvious target for that is the API which is already cached as good as possible and the web frontend which could make use of that via [template caching](https://docs.djangoproject.com/en/3.0/topics/cache/#the-per-view-cache) or JSON requests if we had a SPA.

**Comment by mario** [comment]
I agree @BernhardPosselt - what I'm looking for are quick wins in terms of performance since it's really needed right now and this seems to provide it while being easily reversible.

Would you accept the following:

`    @method_decorator(cache_page(60*60*2))`

on the ListAPIView resources instead? That would give us a significant boost as well.

**Comment by BernhardPosselt** [comment]
No need to do that, that's already cached with varnish.

**Comment by BernhardPosselt** [comment]
Every relevant API call is cached via Etag afaik

**Comment by mario** [comment]
closing for now.

**Pull request closed without merging**
