### PR TITLE
Embed discourse comments

### PR DESCRIPTION
**Pull request by BernhardPosselt**
WIP

There's a weird resizing issue that needs to be fixed. In case anyone is interested feel free to work on it ;)

### CODE REVIEW

**Comment by BernhardPosselt** [comment]
I really dislike the iframe javascript approach, since it makes us vulnerable to uploaded files on discourse. Will close this PR. If integrated, this should be done using the Discourse API from JavaScript

**Comment by BernhardPosselt** [comment]
@LukasReschke can you enable CORS? see https://meta.discourse.org/t/what-are-the-risks-of-enabling-cross-origin-resource-sharing-discourse-enable-cors/41248

**Comment by LukasReschke** [comment]
> @LukasReschke can you enable CORS

Sure. For what origins do you want it enabled?

**Comment by MorrisJobke** [comment]
@BernhardPosselt could this branch be deleted?

**Pull request closed without merging**
