### PR TITLE
Fix #643

### LINKED ISSUE #643: add "Featured" category
In order to find "Featured" labeled apps better, there should be a separate category, making all official apps accessible on one screen.

### PR DESCRIPTION
**Pull request by mario**
Signed-off-by: Mario Danic <mario@lovelyhq.com>

### CODE REVIEW

**Comment by wiswedel** [comment]
@mario Does this cover apps.nextcloud.com or the built-in apps page?

**Comment by mario** [comment]
@wiswedel this covers apps.nextcloud.com

**Comment by mario** [comment]
@wiswedel for updating the built-in apps page, please file a bug against the server as it should be handled there.

**Comment by wiswedel** [comment]
> @wiswedel this covers apps.nextcloud.com

So this just changes the "Featured" checkbox on the top into a "Featured" category on the left, right?

Could my abandoned PR https://github.com/nextcloud/appstore/pull/649 then be useful again and solve the built-in apps page then already?

Will the category assignments for the existing apps auto-update after your PR?

**Comment by mario** [comment]
Kindof. The featured checkbox is still there for all other "links" on the left except for "Featured apps" where I've hidden it.

The category assignments do not change as we've always had isFeatured in the response, so this is basically just a "virtual" category. The same needs to be done on server and should be relatively trivial. So no, your PR would unfortunately not be useful here. But I think @juliushaertl can help us with the server part ^_^

**Comment by mario** [comment]
@wiswedel https://github.com/nextcloud/server/pull/19333

**Comment by blizzz** [comment]
@mario translation updates come from transifex bot, i guess you can just drop the .po files?

**Comment by blizzz** [comment]
deployed

**Pull request merged**
