### PR TITLE
Improve email confirmation message

### LINKED ISSUE #175: Email confirmation email should be improved
I couldn't find the text for the email, so I suspect it's from some library.

Here is the content:

******************
Hello from **apps.nextcloud.com**!

You're receiving this e-mail because user oparoz at apps.nextcloud.com has given **yours as an e-mail address to connect their account**.

To confirm this is correct, go to https://apps.nextcloud.com/confirm-email/Mzc:1bZksL:Y8YI3zMQ0fOllevi3VhZ-dmiSMU/

Thank you from **apps.nextcloud.com**!
**apps.nextcloud.com**
******************

I've highlighted what should be altered.

### PR DESCRIPTION
**Pull request by oparoz**
Fixes #175

### CODE REVIEW

**Comment by BernhardPosselt** [comment]
@oparoz can you test and confirm it locally? mail should be printed to console out

**Comment by oparoz** [comment]
Unfortunately, I don't have the store set up anywhere yet... I'll add a comment here once I do.

**Comment by BernhardPosselt** [comment]
Theres a quick dev setup guide in the docs ;)

**Comment by BernhardPosselt** [comment]
Tested locally and works! Thanks! :+1:

**Pull request merged**
