### PR TITLE
add crl tests

### LINKED ISSUE #258: API: registering an app id and uploading an app release needs to check revoked certificates
In order to prevent old or lost certificates from being abused we need to check if the certificate has been revoked. This has to be done before validating the certificate on app release upload and before registering a new app id.

### PR DESCRIPTION
**Pull request by BernhardPosselt**
Fix #258 

@LukasReschke please commit the certs as described in #258 to this branch :)

### CODE REVIEW

**Comment by BernhardPosselt** [comment]
@LukasReschke netsplit on irc

**Comment by LukasReschke** [comment]
Hehe. Will pull and update ;)

**Comment by BernhardPosselt** [comment]
fix is to open your production.py and find the throttle settings. Replace them with

```py
# how many times a user is allowed to call the app upload route per day
REST_FRAMEWORK['DEFAULT_THROTTLE_RATES']['app_upload'] = '50/day'
# how many times a user is allowed to call the app register route per day
REST_FRAMEWORK['DEFAULT_THROTTLE_RATES']['app_register'] = '50/day'
```

**Comment by BernhardPosselt** [comment]
the current docs for these settings overwrote new settings xD

**Comment by BernhardPosselt** [comment]
fml

**Comment by BernhardPosselt** [comment]
after chagne in production.py you need a server restart ;D

**Comment by BernhardPosselt** [comment]
Btw, netsplit should be over, log back onto irc ;D

**Comment by LukasReschke** [comment]
Updated. Please retry. IRC will work once my bouncer (irccloud.com) is rejoining properly again…

**Comment by BernhardPosselt** [comment]
News app is uploaded :dancer:

**Pull request merged**
